### PR TITLE
Combined parseusb and parsebt data, removed duplicate code from quickgrapher

### PR DESCRIPTION
**Pull request by ghost**
Combined parseusb and parsebt data, also expanded extranalyze function so I could remove duplicate code from quickgrapher.py

### CODE REVIEW

**Review by Mecknavorz — COMMENTED** [review]
I looked over what you did so far and I appreciate the cleaning up some of my old code! It seems like you might still be working on some changes but what you've done so far I'm likely to approve unless you want to add/change other stuff before I merge it.

**Comment by ghost** [comment]
Combined skipCount into the parsedata function and optimized dt calculations. I think this is all I can do for now until I get a better understanding of the code as a whole.

**Review by Mecknavorz — APPROVED** [review]

**Review by Mecknavorz — DISMISSED** [review]
trying to make sure everything is aproved so it can merge proper

**Review by Mecknavorz — APPROVED** [review]
Approving the changes so it can hopefully merge

**Pull request merged**
